// "use client";

import type { Metadata } from "next";
import "./globals.css";
import { ShoppingProvider } from "./context/ShoppingCartContext";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"], // Specify the weights you want to use
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ShoppingProvider>{children}</ShoppingProvider>
      </body>
    </html>
  );
}
